/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class k_art_ch14Ndk_HelloJni */

#ifndef _Included_k_art_ch14Ndk_HelloJni
#define _Included_k_art_ch14Ndk_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     k_art_ch14Ndk_HelloJni
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_k_art_ch14Ndk_HelloJni_get
  (JNIEnv *, jobject);

/*
 * Class:     k_art_ch14Ndk_HelloJni
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_k_art_ch14Ndk_HelloJni_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
